// ENTER YOUR CHECKER FILE, SO THAT IN CASE MULTIPLE SOLUTIONS ARE CORRECT,
// YOU WILL BE ABLE TO JUDGE BOTH SOLUTIONS SEPERATELY AND CHECK FOR THEIR VALIDITY

// PLEASE FOLLOW THE PROBLEM OF OJ, THEN CODE THE CHECKER FILE AS PER IT.